export const ROUTES = {
  about: "/about",
  structure: "/structure",
  rVirtualDom: "/virtualDom",
  rComponents: "/components",
  rProps: "/props",
  rState: "/state",
  rLifeCycle: "/lifeCycle",
  rEvents: "/events",
  rRef: "/ref",
  rMemo: "/memo",
  rCallback: "/callback",
  rContext: "/context",
  rRouter: "/router",
  rForms: "/forms",
  rStorage: "/storage",
  rHoc: "/hoc",
};
